### ISSUE TITLE
新浪的邮箱导入联系人功能挂掉了

### ISSUE THREAD

**Issue by idecent** [kamechb/contacts_cn#2]
hi，kamechb
  你好，我在使用这个gem的时候发现在测试username@sina.cn的时候会报错：
NoMethodError: private method `gsub' called for nil:NilClass
    from /Users/apple/.rvm/gems/ree-1.8.7-2011.03/gems/contacts_cn-1.2.6/lib/contacts/sina.rb:53:in`parse'
    from /Users/apple/.rvm/gems/ree-1.8.7-2011.03/gems/contacts_cn-1.2.6/lib/contacts/sina.rb:35:in `contacts'
    from (irb):6
    from /Users/apple/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/site_ruby/1.8/rubygems/specification.rb:1505

**Comment by kamechb** [comment]
已经解决这个问题
